In [1]:
import pandas as pd
import seaborn as sns

In [2]:
data=pd.read_csv("house.csv")
data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [3]:
data["SalePrice"] = data["SalePrice"].fillna(data["SalePrice"].mean())
data["BsmtFinSF2"]=data["BsmtFinSF2"].fillna(data["BsmtFinSF2"].mean())
data["TotalBsmtSF"]=data["TotalBsmtSF"].fillna(data["TotalBsmtSF"].mean())

In [4]:
data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [5]:
print(data.isna().sum())

Id              0
MSSubClass      0
MSZoning        4
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     1
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [6]:
x=data.drop(columns=["MSZoning","Exterior1st","SalePrice"])
y=data["SalePrice"]

In [7]:
x

,Id,MSSubClass,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
0,0,60,8450,Inside,1Fam,5,2003,2003,0.0,856.0
1,1,20,9600,FR2,1Fam,8,1976,1976,0.0,1262.0
2,2,60,11250,Inside,1Fam,5,2001,2002,0.0,920.0
3,3,70,9550,Corner,1Fam,5,1915,1970,0.0,756.0
4,4,60,14260,FR2,1Fam,5,2000,2000,0.0,1145.0
...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,1936,Inside,Twnhs,7,1970,1970,0.0,546.0
2915,2915,160,1894,Inside,TwnhsE,5,1970,1970,0.0,546.0
2916,2916,20,20000,Inside,1Fam,7,1960,1996,0.0,1224.0
2917,2917,85,10441,Inside,1Fam,5,1992,1992,0.0,912.0
2918,2918,60,9627,Inside,1Fam,5,1993,1994,0.0,996.0

In [8]:
x["LotConfig"]=x["LotConfig"].map({'Inside': 0, 'FR2': 1, 'Corner': 2, 'CulDSac': 3, 'FR3': 4})
x["BldgType"]=x["BldgType"].map({'1Fam':0, '2fmCon':1, 'Duplex':2, 'TwnhsE':3, 'Twnhs':4})

In [9]:
x

,Id,MSSubClass,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
0,0,60,8450,0,0,5,2003,2003,0.0,856.0
1,1,20,9600,1,0,8,1976,1976,0.0,1262.0
2,2,60,11250,0,0,5,2001,2002,0.0,920.0
3,3,70,9550,2,0,5,1915,1970,0.0,756.0
4,4,60,14260,1,0,5,2000,2000,0.0,1145.0
...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,1936,0,4,7,1970,1970,0.0,546.0
2915,2915,160,1894,0,3,5,1970,1970,0.0,546.0
2916,2916,20,20000,0,0,7,1960,1996,0.0,1224.0
2917,2917,85,10441,0,0,5,1992,1992,0.0,912.0
2918,2918,60,9627,0,0,5,1993,1994,0.0,996.0

In [10]:
print(x.isna().sum())

Id              0
MSSubClass      0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
BsmtFinSF2      0
TotalBsmtSF     0
dtype: int64

In [11]:
# split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_predict=model.predict(X_test)

In [14]:
y_predict

array([170963.60262433, 190245.11038904, 162840.64977846, 191800.60800642,
       199135.16254601, 219892.87717721, 137861.46666349, 205731.24585683,
       128334.36937175, 195766.69757991, 175289.52439696, 192531.44203714,
       166548.85808071, 196179.05085188, 192171.15587651, 192726.6501264 ,
       158776.9848901 , 195470.90770748, 139018.0786365 , 164095.33990315,
       203815.32482265, 129779.96137951, 136934.89288425, 203471.86381651,
       202716.42793935, 196736.34624509, 193565.05744422, 136935.6968637 ,
       192263.42461928, 158399.34058468, 225595.04797626, 157838.87754541,
       196079.84918472, 190113.58195823, 204349.01179524, 209209.41481614,
       173330.08121793, 161656.49483187, 154674.54234912, 188568.44695906,
       136512.17680947, 197394.2756335 , 220631.24396058, 175531.20574933,
       169131.0565659 , 186447.3401973 , 194625.78924421, 190638.69632525,
       186051.46821085, 226709.82286186, 173909.8541736 , 170121.21888148,
       144056.18706769, 193786.9483537 , 162405.26874471, 131867.48149991,
       154418.45345977, 175624.68455547, 221742.19740037, 167567.93512041,
       165032.17306559, 136657.84019377, 172262.72096798, 161929.06242196,
       156698.34662695, 202735.28497231, 192237.89142742, 158853.2884517 ,
       183639.1323463 , 182519.53470756, 198934.65862784, 157261.77261469,
       194138.80405792, 214387.15178933, 127511.15278625, 105394.30384263,
       205072.16085856, 141746.40691186, 209838.15040899, 193857.04913142,
       167899.66569078, 196657.46870981, 178727.64525734, 155764.00984711,
       165985.66817329, 192003.30449358, 110183.50953923, 157169.75009883,
       138984.43579786, 180476.34394841, 159132.70723273, 141863.8294101 ,
       148844.45139704, 226472.60548432, 178324.23338889, 190491.61120529,
       177107.59745168, 199711.91458822, 149282.29440201, 178922.92024745,
       167565.50371442, 174678.76907953, 154935.18435387, 198954.75911174,
       185384.82371382, 167031.89027987, 146664.3292146 , 172009.4763822 ,
       223107.79669758, 179506.66849527, 171328.94406021, 155802.24066527,
       201845.37739665, 249787.98004975, 218821.53544791, 162265.65988436,
       153739.64283656, 194725.3897482 , 246432.8517783 , 207357.25669958,
       157189.54006531, 185352.96929333, 204027.35116294, 154130.53033075,
       151912.00472549, 158607.95839824, 150815.03235299, 195483.29984844,
       200439.51410571, 217859.20731734, 159005.00271722, 128149.93619029,
       187267.32588741, 170733.28562374, 164606.74979639, 171705.58776925,
       202960.49867663, 198689.74205856, 235875.18578262, 208349.29823544,
       165587.58944021, 168277.25320365, 148066.5301169 , 198858.41005569,
       220416.03907098, 218105.25134495, 183930.36624467, 237335.1629072 ,
       198717.07596061, 184223.94398662, 166999.14381539, 220924.3074901 ,
       140509.04599289, 163069.40682208, 128164.88157069, 137028.50958767,
       204336.842809  , 200380.97639098, 158691.68568491, 125467.92166771,
       226660.88443275, 230206.87267292, 208926.55348098, 169249.13364957,
       153126.75403479, 161331.44690927, 226490.28471187, 183387.66323036,
       158950.88915763, 133611.9878636 , 153283.66778081, 162619.28163372,
       198329.85482682, 206028.36246366, 201261.25446528, 211765.22082369,
       158737.3926653 , 191136.68247232, 165994.22626878, 206968.9710675 ,
       215577.92343247, 203279.85981139, 159784.51850615, 202429.19094379,
       194913.7482967 , 211193.36315696, 200260.09702885, 228101.71713   ,
       177465.79468744, 164926.97723858, 213011.94741023, 210321.23358982,
       138445.3887203 , 152590.49025211, 194592.86543001, 219076.82012006,
       208348.50369192, 174935.90424998, 254204.25137841, 175276.67758115,
       165656.12954414, 177314.2766271 , 176443.59029774, 164666.36415331,
       173956.72009992, 100923.89612555, 147244.54761373, 180227.63874878,
       148113.48247773, 182156.05642966, 132711.28746244, 177386.34482014,
       209405.52838252, 183355.0093934 , 190991.64105249, 134989.4769025 ,
       205352.87250319, 125099.75493466, 183353.26180609, 183824.29571629,
       127601.9267294 , 183234.97073769, 201647.06865447, 103195.96942349,
       227647.0366126 , 185429.71374212, 188795.71019295, 197944.61044978,
       148651.64458417, 128343.62487236, 149139.06200297, 159221.24748231,
       141582.17965003, 194335.16864215, 156837.2126121 , 171134.89695016,
       168863.81948891, 191513.88502491, 143822.93637747, 131200.31435208,
       217198.30106843, 157764.67498767, 217097.91203494, 218402.94281897,
       235779.08785239, 193545.65996771, 163926.20562707, 203602.3351788 ,
       187136.34426085, 180280.26173101, 200824.63160875, 168252.42010733,
       170678.53532814, 139992.00018215, 230951.73848408, 132774.55851715,
       143439.00437209, 166566.08211133, 210808.60907201, 196472.57815134,
       157609.04758561, 178084.80729285, 159857.71432544, 217861.59314375,
       226028.20737837, 188913.19812659, 183201.7445074 , 164982.16565238,
       208484.88957496, 183675.00783876, 172629.99177716, 151321.6716678 ,
       176994.82441424, 137050.2463079 , 210615.12085035, 202612.96658004,
       160932.12119242, 220481.97053023, 163030.96426189, 185012.17524895,
       220967.0331219 , 168210.28764962, 168807.5176353 , 146164.04646863,
       217874.79895368, 166603.58619031, 206124.06927784, 172366.28150221,
       159920.75210767, 144451.85617252, 174545.34680701, 203028.61916287,
       176496.45986286, 195767.34448484, 189797.89907291, 194797.37850164,
       236625.76106477, 151956.22860359, 167698.1312822 , 173372.56169816,
       181454.93408974, 218770.53772681, 189200.44607228, 213935.33090967,
       153236.98424169, 238648.81825558, 193145.64141255, 217216.07989819,
       164541.11178506, 192165.75680007, 192053.08913228, 175633.88430505,
       191346.21388546, 184947.52143202, 162435.26178622, 175077.00661815,
       141371.34572389, 143032.21132669, 213711.76150262, 160239.61422957,
       174615.25012602, 200412.48446799, 212724.73093542, 114887.2499135 ,
       171320.14048118, 210438.12073917, 195023.28584415, 179942.91587526,
       110979.57303474, 168842.40433152, 148131.48699234, 195985.03336894,
       125410.07950178, 109835.83255496, 209997.66080033, 157386.32290688,
       186504.59274768, 185495.47121341, 177043.42416433, 167092.69321425,
       148474.09983962, 170134.73387206, 168731.73682396, 175468.68738223,
       192297.67249223, 182710.29985083, 180322.56675845, 138435.08361133,
       175674.06795088, 121607.86777388, 169942.2770596 , 188685.2859063 ,
       158964.24993824, 211973.02353966, 206884.95961484, 174508.99675712,
       142354.17664201, 195645.10699278, 147044.73995084, 224758.37473142,
       133098.16159776, 188589.49429395, 183577.47968596, 193884.00270813,
       191666.54143387, 176537.10619636, 180137.82632137, 197126.68975103,
       207798.38372101, 182360.2839338 , 162900.1775874 , 161982.58455209,
       175726.77416785, 145543.71862767, 180515.15582247, 196933.0858413 ,
       172427.37693285, 174324.04533483, 195091.13369742, 189945.59800751,
       169391.17903792, 236700.63866533, 188570.81017988, 181002.01855372,
       141923.67080775, 205894.03209601, 192243.00636853, 161954.26706301,
       163193.59041911, 175724.81443077, 167347.97262917, 214998.87090017,
       205572.68265196, 183493.07546674, 195264.45382419, 152418.90607042,
       200299.70536202, 210869.01769988, 159770.12985896, 182950.05720279,
       190250.76454417, 130829.64889481, 174771.06217048, 186452.5626362 ,
       158855.201644  , 214004.57990415, 166937.90834866, 196503.9515532 ,
       194592.46351065, 136353.71585519, 133903.89471845, 167719.60941763,
       169279.44544449, 203110.51184322, 129618.00132802, 194976.91155246,
       191825.56041768, 191930.41681308, 218872.93981109, 228963.50598155,
       200522.42324814, 153968.03455847, 175327.93799387, 191683.52226065,
       186248.29521843, 209447.28850241, 217656.33891942, 236888.72620485,
       180051.93941605, 182948.92675742, 173396.24017694, 151952.64281567,
       178764.51837627, 204585.1673903 , 171254.23579233, 166220.30547474,
       137425.90501114, 199424.05440792, 158967.2001668 , 142744.90460259,
       181808.984188  , 133117.85751975, 167685.78971215, 226073.78854562,
       176215.40071484, 134016.66461447, 137560.35325854, 211260.29904454,
       190707.97126891, 156533.50900565, 204791.23707594, 162864.06905704,
       194175.95987308, 194071.69688867, 175399.99896474, 151542.47211889,
       160612.81125702, 160288.70255648, 183417.56783082, 139834.4807771 ,
       164098.88037577, 197706.96961871, 164995.84998517, 242653.14299596,
       196389.74627918, 138643.18110147, 172022.16535883, 271406.59168823,
       198658.05664543, 152491.98735971, 248382.23791818, 157826.41619174,
       201496.83600543, 204851.92686149, 205515.2649221 , 202627.58411469,
       172548.68360833, 225617.64261924, 195238.84954379, 140963.42101591,
       223695.92301352, 182486.61222963, 150244.12009651, 217719.23255058,
       166500.1802037 , 163136.77294141, 171086.51746221, 162447.78851051,
       173889.27822675, 197816.89984776, 211344.66866575, 182373.46166056,
       215868.6155258 , 187644.23590941, 380036.03045538, 224898.67522362,
       185333.76860397, 209308.89702683, 144287.06154112, 176680.54258397,
       145581.38123076, 215220.03950489, 200464.69884599, 222366.20996092,
       131223.32976258, 189920.48561453, 143591.49491743, 204179.184934  ,
       149261.89377699, 155070.93923504, 199794.94041096, 198327.66633119,
       181716.62734716, 178216.5929155 , 214674.98033473, 200906.84384315,
       177072.43385887, 213616.15655809, 169493.26539707, 221168.79145812,
       140241.98197642, 171632.82482688, 187925.16522229, 184692.58648233,
       165065.78910781, 148505.31699242, 230978.27128415, 194464.50965662,
       198328.15201446, 161166.14908768, 126191.4754882 , 163739.65085352,
       264004.33154524, 187364.22296824, 191837.13986049, 162968.22612612,
       138014.78697377, 163519.28576828, 213381.67022097, 200022.45263142,
       174510.52642287, 167164.27266865, 190195.84881626, 173938.88976481,
       165002.33715816, 146683.75958399, 179471.20862956, 148592.84987732,
       148893.04792229, 234636.71616436, 212985.04840403, 200359.36420558,
       165091.7348418 , 178914.00776027, 232609.17911765, 118873.52651764,
       171028.7385677 , 195951.26942077, 140948.61225192, 176072.861994  ,
       207483.15937789, 196497.25667672, 166921.36144737, 163658.07561276,
       157785.12255708, 173721.65432755, 131126.04684459, 152388.62270735,
       167522.65705803, 107867.60521447, 200753.27606957, 199243.09935679,
       149005.54568322, 172835.48454401, 182662.46697618, 165864.1524782 ,
       176896.35019394, 199796.53668344, 202464.90808366, 153850.4310598 ,
       235376.56189929, 232042.8734221 , 105566.06603494, 201789.70328249])

In [17]:
y_test

2437    180921.19589
2470    180921.19589
2359    180921.19589
789     187500.00000
1642    180921.19589
            ...
2880    180921.19589
2295    180921.19589
2222    180921.19589
1090     92900.00000
542     213250.00000
Name: SalePrice, Length: 584, dtype: float64

In [18]:
from sklearn.metrics import r2_score
r2=r2_score(y_test, y_predict)
print("r2 value:",r2)

r2 value: 0.3365144772126494